begin;

create table if not exists public.products (
  id text primary key,
  name text not null,
  description text not null,
  category text not null check (category in ('Chêne', 'Hêtre', 'Frêne', 'Charme', 'Mélange')),
  stock numeric(10, 2) not null default 0 check (stock >= 0),
  updated_at timestamptz not null default now()
);

create table if not exists public.product_prices (
  product_id text not null references public.products(id) on delete cascade,
  log_length text not null check (log_length in ('25 cm', '33 cm', '40 cm', '50 cm', '1 m')),
  price_per_m3 numeric(10, 2) not null check (price_per_m3 >= 0),
  primary key (product_id, log_length)
);

create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  product_id text not null references public.products(id) on delete cascade,
  path text not null,
  is_primary boolean not null default false,
  created_at timestamptz not null default now()
);

create unique index if not exists one_primary_image_per_product
  on public.product_images(product_id) where is_primary;

create table if not exists public.orders (
  id text primary key,
  customer_name text not null,
  phone text not null,
  email text not null,
  postal_code text not null,
  address text not null,
  delivery_notes text not null default '',
  items jsonb not null,
  delivery_fee numeric(10, 2) not null default 0 check (delivery_fee >= 0),
  total numeric(10, 2) not null check (total >= 0),
  status text not null default 'new'
    check (status in ('new', 'confirmed', 'delivered', 'cancelled')),
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;
alter table public.product_prices enable row level security;
alter table public.product_images enable row level security;
alter table public.orders enable row level security;

insert into public.products (id, name, description, category, stock)
values
  ('chene', 'Chêne séché', 'Une combustion lente et régulière, idéale pour les longues soirées.', 'Chêne', 20),
  ('hetre', 'Hêtre séché', 'Une chaleur homogène et un feu facile à maîtriser au quotidien.', 'Hêtre', 20),
  ('frene', 'Frêne séché', 'Un bois polyvalent qui s’allume facilement et chauffe efficacement.', 'Frêne', 20),
  ('charme', 'Charme séché', 'Un bois dense à la belle tenue au feu et au pouvoir calorifique élevé.', 'Charme', 20),
  ('melange', 'Mélange de feuillus', 'Un assortiment équilibré de bois durs pour toute la saison.', 'Mélange', 20)
on conflict (id) do nothing;

insert into public.product_prices (product_id, log_length, price_per_m3)
values
  ('chene', '25 cm', 92), ('chene', '33 cm', 84), ('chene', '40 cm', 80), ('chene', '50 cm', 74), ('chene', '1 m', 66),
  ('hetre', '25 cm', 84), ('hetre', '33 cm', 76), ('hetre', '40 cm', 72), ('hetre', '50 cm', 66), ('hetre', '1 m', 58),
  ('frene', '25 cm', 88), ('frene', '33 cm', 80), ('frene', '40 cm', 76), ('frene', '50 cm', 70), ('frene', '1 m', 62),
  ('charme', '25 cm', 96), ('charme', '33 cm', 88), ('charme', '40 cm', 84), ('charme', '50 cm', 78), ('charme', '1 m', 70),
  ('melange', '25 cm', 82), ('melange', '33 cm', 74), ('melange', '40 cm', 70), ('melange', '50 cm', 64), ('melange', '1 m', 56)
on conflict (product_id, log_length) do nothing;

insert into public.product_images (product_id, path, is_primary)
select seed.product_id, seed.path, true
from (values
  ('chene', '/images/catalog/chene.jpeg'),
  ('hetre', '/images/catalog/hetre.jpeg'),
  ('frene', '/images/catalog/frene.jpeg'),
  ('charme', '/images/catalog/charme.jpeg'),
  ('melange', '/images/catalog/melange.jpeg')
) as seed(product_id, path)
where not exists (
  select 1 from public.product_images image
  where image.product_id = seed.product_id
);

create or replace function public.admin_update_catalog_product(
  p_product_id text,
  p_name text,
  p_description text,
  p_category text,
  p_stock numeric,
  p_prices jsonb
) returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_length text;
  v_price numeric;
begin
  update public.products
  set name = p_name,
      description = p_description,
      category = p_category,
      stock = p_stock,
      updated_at = now()
  where id = p_product_id;
  if not found then
    raise exception 'Produit introuvable.';
  end if;

  foreach v_length in array array['25 cm', '33 cm', '40 cm', '50 cm', '1 m']
  loop
    if not (p_prices ? v_length) then
      raise exception 'Tarif manquant pour %.', v_length;
    end if;
    v_price := (p_prices ->> v_length)::numeric;
    insert into public.product_prices (product_id, log_length, price_per_m3)
    values (p_product_id, v_length, v_price)
    on conflict (product_id, log_length)
    do update set price_per_m3 = excluded.price_per_m3;
  end loop;
end;
$$;

create or replace function public.admin_add_product_image(
  p_product_id text,
  p_path text,
  p_replace_image_id bigint default null,
  p_set_primary boolean default false
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_removed_path text := null;
  v_primary boolean;
  v_image_count bigint;
begin
  perform 1 from public.products where id = p_product_id for update;
  if not found then
    raise exception 'Produit introuvable.';
  end if;

  if p_replace_image_id is not null then
    select path into v_removed_path
    from public.product_images
    where id = p_replace_image_id and product_id = p_product_id
    for update;
    if not found then
      raise exception 'Photo à remplacer introuvable.';
    end if;
    delete from public.product_images
    where id = p_replace_image_id and product_id = p_product_id;
  end if;

  select count(*) into v_image_count
  from public.product_images where product_id = p_product_id;
  v_primary := p_set_primary or v_image_count = 0;
  if v_primary then
    update public.product_images
    set is_primary = false
    where product_id = p_product_id and is_primary;
  end if;
  insert into public.product_images (product_id, path, is_primary)
  values (p_product_id, p_path, v_primary);
  return jsonb_build_object('removedPath', v_removed_path);
end;
$$;

create or replace function public.admin_set_primary_product_image(
  p_product_id text,
  p_image_id bigint
) returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  perform 1 from public.products where id = p_product_id for update;
  if not found then
    raise exception 'Produit introuvable.';
  end if;
  if not exists (
    select 1 from public.product_images
    where id = p_image_id and product_id = p_product_id
  ) then
    raise exception 'Photo introuvable.';
  end if;
  update public.product_images set is_primary = false
  where product_id = p_product_id and is_primary;
  update public.product_images set is_primary = true
  where id = p_image_id and product_id = p_product_id;
end;
$$;

create or replace function public.admin_delete_product_image(
  p_product_id text,
  p_image_id bigint
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_removed_path text;
  v_was_primary boolean;
  v_remaining_id bigint;
  v_image_count bigint;
begin
  perform 1 from public.products where id = p_product_id for update;
  if not found then
    raise exception 'Produit introuvable.';
  end if;
  select path, is_primary into v_removed_path, v_was_primary
  from public.product_images
  where id = p_image_id and product_id = p_product_id
  for update;
  if not found then
    raise exception 'Photo introuvable.';
  end if;
  select count(*) into v_image_count
  from public.product_images where product_id = p_product_id;
  if v_image_count <= 1 then
    raise exception 'Chaque produit doit conserver au moins une photo.';
  end if;
  if v_was_primary then
    select id into v_remaining_id
    from public.product_images
    where product_id = p_product_id and id <> p_image_id
    order by id limit 1;
  end if;
  delete from public.product_images where id = p_image_id;
  if v_remaining_id is not null then
    update public.product_images set is_primary = true where id = v_remaining_id;
  end if;
  return jsonb_build_object(
    'removedPath', v_removed_path,
    'replacementPrimary', v_was_primary
  );
end;
$$;

create or replace function public.create_catalog_order(
  p_customer_name text,
  p_phone text,
  p_email text,
  p_postal_code text,
  p_address text,
  p_delivery_notes text,
  p_items jsonb
) returns table(order_id text, total numeric, delivery_fee numeric)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_requested record;
  v_product record;
  v_price numeric;
  v_items jsonb := '[]'::jsonb;
  v_line_total numeric;
  v_subtotal numeric := 0;
  v_delivery_fee numeric;
  v_total numeric;
  v_order_id text;
begin
  for v_requested in
    select distinct item.product_id
    from jsonb_to_recordset(p_items) as item(product_id text, log_length text, volume numeric)
    order by item.product_id
  loop
    perform 1 from public.products where id = v_requested.product_id for update;
    if not found then
      raise exception 'Un produit de votre panier n’existe plus.';
    end if;
  end loop;

  for v_requested in
    select item.product_id, sum(item.volume) as volume
    from jsonb_to_recordset(p_items) as item(product_id text, log_length text, volume numeric)
    group by item.product_id
    order by item.product_id
  loop
    select stock, name into v_product
    from public.products where id = v_requested.product_id;
    if v_product.stock < v_requested.volume then
      raise exception 'Stock insuffisant pour %.', v_product.name;
    end if;
  end loop;

  for v_requested in
    select item.product_id, item.log_length, item.volume
    from jsonb_to_recordset(p_items) as item(product_id text, log_length text, volume numeric)
  loop
    select product.name, product.category, price.price_per_m3
      into v_product
    from public.products product
    join public.product_prices price
      on price.product_id = product.id
    where product.id = v_requested.product_id
      and price.log_length = v_requested.log_length;
    if not found then
      raise exception 'Tarif indisponible pour une sélection.';
    end if;

    v_line_total := round(v_product.price_per_m3 * v_requested.volume, 2);
    v_subtotal := v_subtotal + v_line_total;
    v_items := v_items || jsonb_build_array(jsonb_build_object(
      'productId', v_requested.product_id,
      'name', v_product.name,
      'category', v_product.category,
      'logLength', v_requested.log_length,
      'volume', v_requested.volume,
      'unitPrice', v_product.price_per_m3,
      'total', v_line_total
    ));
  end loop;

  v_subtotal := round(v_subtotal, 2);
  v_delivery_fee := case when v_subtotal >= 150 or v_subtotal = 0 then 0 else 12 end;
  v_total := round(v_subtotal + v_delivery_fee, 2);
  v_order_id := 'BB-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8));

  insert into public.orders (
    id, customer_name, phone, email, postal_code, address,
    delivery_notes, items, delivery_fee, total
  ) values (
    v_order_id, p_customer_name, p_phone, p_email, p_postal_code, p_address,
    p_delivery_notes, v_items, v_delivery_fee, v_total
  );

  for v_requested in
    select item.product_id, sum(item.volume) as volume
    from jsonb_to_recordset(p_items) as item(product_id text, log_length text, volume numeric)
    group by item.product_id
  loop
    update public.products
    set stock = stock - v_requested.volume,
        updated_at = now()
    where id = v_requested.product_id;
  end loop;

  return query select v_order_id, v_total, v_delivery_fee;
end;
$$;

create or replace function public.admin_update_order_status(
  p_order_id text,
  p_status text
) returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_current_status text;
  v_items jsonb;
  v_requested record;
  v_product record;
begin
  if p_status not in ('new', 'confirmed', 'delivered', 'cancelled') then
    raise exception 'Statut de commande invalide.';
  end if;
  select status, items into v_current_status, v_items
  from public.orders where id = p_order_id for update;
  if not found then
    raise exception 'Commande introuvable.';
  end if;

  if v_current_status <> 'cancelled' and p_status = 'cancelled' then
    for v_requested in
      select item.product_id, sum(item.volume) as volume
      from jsonb_to_recordset(v_items) as item(product_id text, volume numeric)
      group by item.product_id
      order by item.product_id
    loop
      update public.products
      set stock = stock + v_requested.volume,
          updated_at = now()
      where id = v_requested.product_id;
    end loop;
  elsif v_current_status = 'cancelled' and p_status <> 'cancelled' then
    for v_requested in
      select distinct item.product_id
      from jsonb_to_recordset(v_items) as item(product_id text, volume numeric)
      order by item.product_id
    loop
      perform 1 from public.products where id = v_requested.product_id for update;
      if not found then
        raise exception 'Un produit de la commande n’existe plus.';
      end if;
    end loop;
    for v_requested in
      select item.product_id, sum(item.volume) as volume
      from jsonb_to_recordset(v_items) as item(product_id text, volume numeric)
      group by item.product_id
    loop
      select stock, name into v_product
      from public.products where id = v_requested.product_id;
      if v_product.stock < v_requested.volume then
        raise exception 'Stock insuffisant pour réactiver la commande (%).', v_product.name;
      end if;
      update public.products
      set stock = stock - v_requested.volume,
          updated_at = now()
      where id = v_requested.product_id;
    end loop;
  end if;

  update public.orders set status = p_status where id = p_order_id;
end;
$$;

revoke all on public.products, public.product_prices, public.product_images, public.orders
  from anon, authenticated;
grant all on public.products, public.product_prices, public.product_images, public.orders
  to service_role;

revoke all on function public.admin_update_catalog_product(text, text, text, text, numeric, jsonb) from public, anon, authenticated;
revoke all on function public.admin_add_product_image(text, text, bigint, boolean) from public, anon, authenticated;
revoke all on function public.admin_set_primary_product_image(text, bigint) from public, anon, authenticated;
revoke all on function public.admin_delete_product_image(text, bigint) from public, anon, authenticated;
revoke all on function public.create_catalog_order(text, text, text, text, text, text, jsonb) from public, anon, authenticated;
revoke all on function public.admin_update_order_status(text, text) from public, anon, authenticated;
grant execute on function public.admin_update_catalog_product(text, text, text, text, numeric, jsonb) to service_role;
grant execute on function public.admin_add_product_image(text, text, bigint, boolean) to service_role;
grant execute on function public.admin_set_primary_product_image(text, bigint) to service_role;
grant execute on function public.admin_delete_product_image(text, bigint) to service_role;
grant execute on function public.create_catalog_order(text, text, text, text, text, text, jsonb) to service_role;
grant execute on function public.admin_update_order_status(text, text) to service_role;

commit;
