import type { Metadata } from 'next';
import Link from 'next/link';
import Image from 'next/image';
import { Plus, Pencil, PackageOpen } from 'lucide-react';
import { getAllWoodProductsAdmin } from '@/lib/data/admin-wood-products';
import { formatWoodPrice } from '@/lib/data/wood-products';
export const metadata:Metadata={title:'Catalogue bois'};
export const dynamic='force-dynamic';
export default async function AdminWoodProductsPage(){const {products,error}=await getAllWoodProductsAdmin();return <div><header className="mb-6 flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-[#806344]">HolzNest</p><h1 className="mt-1 text-2xl font-extrabold text-ink-900">Catalogue bois</h1><p className="mt-1 text-sm text-ink-500">{error??`${products.length} produit${products.length===1?'':'s'} · gérer textes, tarifs, photos et publication`}</p></div><Link href="/admin/bois/nouveau" className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-[#21492d] px-4 py-2.5 text-sm font-semibold text-white"><Plus size={17}/> Ajouter un produit</Link></header>{error?<div role="alert" className="rounded-xl border border-amber-300 bg-amber-50 p-5 text-sm text-amber-900">{error}</div>:products.length===0?<div className="rounded-2xl border border-dashed border-ink-200 bg-white p-10 text-center"><PackageOpen className="mx-auto h-9 w-9 text-ink-400"/><h2 className="mt-3 font-bold text-ink-900">Aucun produit</h2><p className="mt-1 text-sm text-ink-500">Ajoutez votre première essence de bois.</p></div>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{products.map(product=>{const image=product.wood_product_images.find(item=>item.is_primary)??product.wood_product_images[0];return <article key={product.id} className="overflow-hidden rounded-2xl border border-ink-100 bg-white shadow-sm"><div className="relative aspect-[16/8] bg-sand-100">{image&&<Image src={image.url} alt={image.alt_text??product.name} fill sizes="450px" className="object-cover"/>}<span className={`absolute left-3 top-3 rounded-full px-2.5 py-1 text-xs font-semibold ${product.is_published?'bg-emerald-100 text-emerald-800':'bg-white text-ink-700'}`}>{product.is_published?'Publié':'Brouillon'}</span></div><div className="p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="text-lg font-bold text-ink-900">{product.name}</h2><p className="mt-1 line-clamp-2 text-sm text-ink-500">{product.short_description||'Sans description'}</p></div><strong className="whitespace-nowrap text-sm text-ink-800">{formatWoodPrice(product.price_per_m3)} / m³</strong></div><div className="mt-4 flex items-center justify-between border-t border-ink-100 pt-3 text-xs text-ink-500"><span>{product.wood_product_images.length} photo(s) · {product.in_stock?'En stock':'Épuisé'}</span><Link href={`/admin/bois/${product.id}`} className="inline-flex min-h-9 items-center gap-1.5 rounded-lg border border-ink-200 px-3 font-semibold text-ink-700 hover:bg-sand-100"><Pencil size={14}/> Modifier</Link></div></div></article>;})}</div>}</div>}
