import Image from 'next/image';
import Link from 'next/link';
import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { ArrowLeft, Droplets, Flame, PackageCheck, Truck } from 'lucide-react';
import { getPublishedWoodProduct } from '@/lib/data/wood-products';
import { ProductPurchase } from '@/components/wood/product-purchase';
export const dynamic='force-dynamic';
type PageProps={params:{slug:string}};
export async function generateMetadata({params}:PageProps):Promise<Metadata>{const product=await getPublishedWoodProduct(params.slug);return product?{title:`${product.name} — Bois de chauffage`,description:product.short_description,openGraph:{images:product.wood_product_images[0]?[product.wood_product_images[0].url]:undefined}}:{title:'Essence introuvable'};}
export default async function WoodProductPage({params}:PageProps){const product=await getPublishedWoodProduct(params.slug);if(!product)notFound();const cover=product.wood_product_images.find(image=>image.is_primary)??product.wood_product_images[0];return <main className="container-app py-7 sm:py-10"><Link href="/catalogue" className="mb-5 inline-flex items-center gap-2 text-sm text-[#655f55] hover:text-[#1f492c]"><ArrowLeft size={16}/> Retour aux essences</Link><div className="grid items-start gap-8 lg:grid-cols-2 lg:gap-12"><div className="relative aspect-[4/3] overflow-hidden rounded-[22px] bg-[#e6ddcf]">{cover?<Image src={cover.url} alt={cover.alt_text??`Bûches de ${product.name}`} fill priority sizes="(max-width: 1023px) 100vw, 50vw" className="object-cover"/>:<div className="flex h-full items-center justify-center text-ink-400">Photo à ajouter depuis l’administration</div>}</div><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#bd682b]">{product.name}</p><h1 className="wood-heading mt-1 text-5xl font-medium text-[#102b1e] sm:text-6xl">{product.name}</h1><p className="mt-4 max-w-2xl text-[15px] leading-6 text-[#645f55]">{product.description}</p><div className="mt-5 flex flex-wrap gap-2">{product.moisture_percent!=null&&<span className="wood-chip wood-chip-green"><Droplets size={14}/>Humidité ≤ {product.moisture_percent}%</span>}{product.delivery_available&&<span className="wood-chip wood-chip-orange"><Truck size={14}/>Livraison disponible</span>}{product.calorific_value_kwh!=null&&<span className="wood-chip wood-chip-red"><Flame size={14}/>{product.calorific_value_kwh} kWh/m³</span>}{product.in_stock&&<span className="wood-chip wood-chip-green"><PackageCheck size={14}/>{product.stock_m3!=null?`${product.stock_m3} m³ en stock`:'En stock'}</span>}</div>{product.calorific_value_kwh!=null&&<p className="mt-5 text-sm text-[#655f55]">Pouvoir calorifique estimé : <strong>{product.calorific_value_kwh} kWh / m³</strong></p>}<div className="mt-7"><ProductPurchase product={product}/></div><p className="mt-3 text-xs text-[#766e62]">Disponibilité et livraison confirmées selon la destination et la quantité.</p></div></div></main>;}
