'use client';
import Image from 'next/image';
import { useRef, useState } from 'react';
import { ImagePlus, Star, Trash2 } from 'lucide-react';
import { toast } from 'sonner';
import { deleteWoodProductImage, setPrimaryWoodProductImage, uploadWoodProductImage } from '@/actions/admin-wood-products';
import type { WoodProductImageRecord } from '@/types/database';
export function WoodImageManager({productId,initialImages}:{productId:string;initialImages:WoodProductImageRecord[]}){
  const [images,setImages]=useState([...initialImages].sort((a,b)=>a.sort_order-b.sort_order));
  const [busy,setBusy]=useState(false); const input=useRef<HTMLInputElement>(null);
  async function upload(file?:File){if(!file||busy)return;setBusy(true);try{const form=new FormData();form.append('images',file);const result=await uploadWoodProductImage(productId,form);if(result.success&&'image'in result){setImages(old=>[...old,result.image]);toast.success(result.message);}else toast.error(result.message);}catch{toast.error('Envoi de la photo interrompu.');}finally{setBusy(false);if(input.current)input.current.value='';}}
  async function makePrimary(id:string){if(busy)return;const previous=images;setImages(old=>old.map(image=>({...image,is_primary:image.id===id})));setBusy(true);try{const result=await setPrimaryWoodProductImage(productId,id);if(result.success)toast.success(result.message);else{setImages(previous);toast.error(result.message);}}catch{setImages(previous);toast.error('La photo principale n’a pas pu être modifiée.');}finally{setBusy(false);}}
  async function remove(id:string){if(busy||!window.confirm('Supprimer cette photo ?'))return;const previous=images;setImages(old=>old.filter(image=>image.id!==id));setBusy(true);try{const result=await deleteWoodProductImage(productId,id);if(result.success)toast.success(result.message);else{setImages(previous);toast.error(result.message);}}catch{setImages(previous);toast.error('La photo n’a pas pu être supprimée.');}finally{setBusy(false);}}
  return <section className="rounded-2xl border border-ink-100 bg-white p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold text-ink-900">Photos du produit</h2><p className="mt-1 text-sm text-ink-500">JPG, PNG, WebP ou AVIF · 10 Mo maximum.</p></div><button type="button" onClick={()=>input.current?.click()} disabled={busy} className="inline-flex min-h-10 items-center gap-2 rounded-xl bg-[#21492d] px-4 py-2 text-sm font-semibold text-white disabled:opacity-50"><ImagePlus size={16}/>{busy?'Traitement…':'Ajouter une photo'}</button><input ref={input} type="file" accept="image/jpeg,image/png,image/webp,image/avif" className="hidden" onChange={e=>void upload(e.target.files?.[0])}/></div>
    {images.length===0?<div className="mt-5 rounded-xl border border-dashed border-ink-200 p-8 text-center text-sm text-ink-500">Aucune photo pour le moment. Ajoutez une image pour remplacer l’illustration provisoire.</div>:<div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{images.map(image=><article key={image.id} className="overflow-hidden rounded-xl border border-ink-100"><div className="relative aspect-[4/3] bg-sand-100"><Image src={image.url} alt={image.alt_text??''} fill sizes="300px" className="object-cover"/>{image.is_primary&&<span className="absolute left-2 top-2 rounded-full bg-white px-2.5 py-1 text-xs font-semibold text-ink-800">Photo principale</span>}</div><div className="flex gap-2 p-3"><button type="button" disabled={busy||image.is_primary} onClick={()=>void makePrimary(image.id)} className="inline-flex min-h-9 flex-1 items-center justify-center gap-1.5 rounded-lg border border-ink-200 px-2 text-xs font-medium text-ink-700 disabled:opacity-50"><Star size={14}/>{image.is_primary?'Principale':'Définir principale'}</button><button type="button" disabled={busy} onClick={()=>void remove(image.id)} aria-label="Supprimer la photo" className="flex h-9 w-9 items-center justify-center rounded-lg border border-red-200 text-red-700 disabled:opacity-50"><Trash2 size={15}/></button></div></article>)}</div>}
  </section>;
}
